# Generated by Django 5.0.4 on 2024-05-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstace_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstace',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
